### ISSUE TITLE
Extension removed from the Google Chrome store

### ISSUE THREAD

**Issue by DougNix** [herrherrmann/omnivore-list-popup#22]
It appears that the plugin has been removed from the Google Chrome store. Hopefully, you'll be making it available there again soon.

**Comment by herrherrmann** [comment]
You’re absolutely right! I tried to keep a broken version from being released to the Chrome Web Store, but that meant that I accidentally unpublished the current version … Right now, I have to wait until the Chrome team checks the broken version, just for me to re-upload a working version (1.2.2). I suspect that I can upload the fixed version tomorrow.

Sorry for the inconvenience!

**Comment by herrherrmann** [comment]
Version 1.2.2 should be available in the Chrome Web Store now! 🎉
https://chrome.google.com/webstore/detail/omnivore-list-popup/dnfckbihnohkfoaclfckbcebclmhleni
