### ISSUE TITLE
Saved page indicator

### ISSUE THREAD

**Issue by robsonsobral** [herrherrmann/omnivore-list-popup#5]
Hi! I'm testing your add-on. Thank you for coding it!

Can you, please, add a saved page indicator to the button on the toolbar, like Raindrop does?

![image](https://github.com/herrherrmann/omnivore-list-popup/assets/931642/70f230d4-6362-4183-9fb0-3f4e8ce3e87e)

The required permissions are asked on function activation.

![image](https://github.com/herrherrmann/omnivore-list-popup/assets/931642/14c8c8e6-8962-47fd-9efe-f9e7b7bf2347)

Thank you so much!

**Comment by herrherrmann** [comment]
Heya! Good point, and this idea is even already in the list of [Todos & Ideas](https://github.com/herrherrmann/omnivore-list-popup#todos--ideas). :)

> The required permissions are asked on function activation.

Ah, you mean this is how it currently works in Raindrop.io? I think it definitely makes sense to build this indicator as an optional feature (to be able to turn it off, if desired).

**Comment by robsonsobral** [comment]
> Ah, you mean this is how it currently works in Raindrop.io? I think it definitely makes sense to build this indicator as an optional feature (to be able to turn it off, if desired).

Oh, yeah! I'm sorry! On Raindrop, the permission is asked only when you try to activate the feature.

I'm sorry for the redundant issue!

**Comment by herrherrmann** [comment]
No need to be sorry at all! It’s good that you reached out, so now I know that there’s demand for this feature. :)
